version: '3.8'

services:
  labinc-db:
    image: postgres:latest
    container_name: labinc-container
    ports:
      - "5431:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: BDLabInc